// 微前端/qiankun/vue3-dome/src/App.vue
<template>
  <div>
    <div class="nav" v-if="token">
      <div class="menu">
        <router-link to="/">Parent Home</router-link>
      </div>
      <div class="menu">
        <router-link to="/about">Parent About</router-link>
      </div>
      <div class="menu">
        <router-link to="/vue2-micro-app">Child Home</router-link>
      </div>
      <div class="menu">
        <router-link to="/vue2-micro-app/about">Child About</router-link>
      </div>
      <div class="menu">
        <router-link to="/react-micro-app">Child Home</router-link>
      </div>
      <div class="menu">
        <router-link to="/react-micro-app/about">Child About</router-link>
      </div>
    </div>
    <div class="container">
      <div class="header" v-if="token">Parent Header</div>
      <div class="router-view">
        <router-view />
        <div id="micro-container"></div>
      </div>
    </div>
  </div>
</template>
<script>
import { defineComponent, computed } from "vue";
import { useStore } from "vuex";

export default defineComponent({
  setup() {
    const store = useStore();
    return {
      token: computed(() => store.state.token),
    };
  },
});
</script>

<style>
#app {
  display: flex;
  width: 100%;
  height: 100%;
}
.nav {
  width: 300px;
  height: 100%;
  border-right: 2px solid red;
}
.menu {
  width: 100%;
  background: gray;
  margin-bottom: 10px;
  height: 30px;
}
.menu > a {
  color: white;
}
.container {
  flex: 1;
}
.header {
  background: #ada5a5;
  width: 100%;
  height: 50px;
  color: white;
}
</style>

// 微前端/qiankun/react-dome/src/App.jsx
import Home from './view/home';
import About from './view/about';
import Login from './view/login';
import { connect } from 'react-redux'
import { BrowserRouter as Routers, Route, Redirect, Link, Switch, } from 'react-router-dom'

import './style/App.css'


function App(props) {
  const { token } = props

  return (
    <Routers basename={window.__POWERED_BY_QIANKUN__ ? '/react-micro-app' : '/'}>
      {
        !token && <Redirect to="/login" />
      }
      {token && <ul className="nav">
        <li className="menu">
          <Link to="/">React Home</Link>
        </li>
        <li className="menu">
          <Link to="/about">React about</Link>
        </li>

      </ul>}
      <div className="container">
        {token && <div className="header"  >Child Header</div>}
        <div className="router-view">
          <Switch>
            <Route path='/' exact component={Home} >
            </Route>
            <Route path='/about' component={About}>
            </Route>
            <Route path='/login' component={Login}>
            </Route>
          </Switch>
        </div>
      </div>
    </Routers>

  );
}
export default connect((state) => state.token)(App);
