// 微前端/qiankun/react-dome/src/view/login/index.jsx
import { useState } from "react"


function Login(props) {
    const [username, setName] = useState('')
    const [password, setPass] = useState('')
    function login() {
        if (usernamez && password.value) {
            // store.commit("setToken", "123456");
            // router.push({
            //   path: "/",
            // });
            console.log(props);
        }
    }
    return (
        <div>
            登录页
            <div>用户名：<input onChange={(e) => setName(e.target.value)} value={username} /></div>
            <div>密码：<input onChange={(e) => setPass(e.target.value)} value={password} /></div>
            <div><button onClick={login}>登录</button></div>
        </div >
    )
}
export default Login

// 微前端/qiankun/vue3-dome/src/views/login.vue
<template>
  <div>
    登录页
    <div>用户名：<input v-model="username" /></div>
    <div>密码：<input v-model="password" /></div>
    <div><button @click="login">登录</button></div>
  </div>
</template>

<script>
import { ref } from "@vue/reactivity";
import { useStore } from "vuex";
import { useRouter } from "vue-router";
export default {
  setup() {
    const username = ref("");
    const password = ref("");
    const store = useStore();
    const router = useRouter();
    const login = () => {
      if (username.value && password.value) {
        store.commit("setToken", "123456");
        router.push({
          path: "/",
        });
      }
    };
    return {
      username,
      password,
      login,
    };
  },
};
</script>

<style>
</style>
