// 微前端/qiankun/react-dome/src/view/login/index.jsx
import { useState } from "react"


function Login(props) {
    const [username, setName] = useState('')
    const [password, setPass] = useState('')
    function login() {
        if (usernamez && password.value) {
            // store.commit("setToken", "123456");
            // router.push({
            //   path: "/",
            // });
            console.log(props);
        }
    }
    return (
        <div>
            登录页
            <div>用户名：<input onChange={(e) => setName(e.target.value)} value={username} /></div>
            <div>密码：<input onChange={(e) => setPass(e.target.value)} value={password} /></div>
            <div><button onClick={login}>登录</button></div>
        </div >
    )
}
export default Login

// 微前端/qiankun/vue2-dome/src/views/login.vue
<template>
  <div>
    登录页
    <div>用户名：<input v-model="username" /></div>
    <div>密码：<input v-model="password" /></div>
    <div><button @click="login">登录</button></div>
  </div>
</template>
  
  <script>
import { mapMutations } from "vuex";
export default {
  data() {
    return {
      username: "",
      password: "",
    };
  },
  methods: {
    ...mapMutations(["setToken"]),
    login() {
      if (this.username && this.password) {
        this.setToken("123456");
        this.$router.push({
          path: "/",
        });
      }
    },
  },
};
</script>
  
  <style lang="scss" scoped></style>
