// react-learn/src/reduxAsync/containers/App.js
/*
 * @Author: your name
 * @Date: 2021-01-04 17:25:48
 * @LastEditTime: 2021-01-04 17:27:43
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: \learn\react-learn\src\reduxAsync\containers\App.js
 */
import {Component} from 'react'


class App extends Component{
    


    render(){
        return<>1</>
    }
}

// WebpackDome/webpack-vue/src/App.vue
<!--
 * @Author: your name
 * @Date: 2021-01-11 10:14:14
 * @LastEditTime: 2021-01-11 15:16:15
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: \learn\WebpackDome\webpack-vue\src\App.vue
-->
<template>
  <div class="example">
      <h1>{{ msg }}</h1>

  <img src="./assets/616945.png" alt="" srcset="">

  </div>
</template>

<script>
export default {
    name: "app",
  data () {
    return {
      msg: 'Hello world!'
    }
  }
}
</script>

<style>
.example {
  color: red;
}
</style>
