// WebpackDome/webpack-vue/src/App.vue
<!--
 * @Author: your name
 * @Date: 2021-01-11 10:14:14
 * @LastEditTime: 2021-01-11 15:16:15
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: \learn\WebpackDome\webpack-vue\src\App.vue
-->
<template>
  <div class="example">
      <h1>{{ msg }}</h1>

  <img src="./assets/616945.png" alt="" srcset="">

  </div>
</template>

<script>
export default {
    name: "app",
  data () {
    return {
      msg: 'Hello world!'
    }
  }
}
</script>

<style>
.example {
  color: red;
}
</style>

// react-learn/src/redux/components/App.js
/*
 * @Author: your name
 * @Date: 2020-12-30 17:34:18
 * @LastEditTime: 2020-12-30 17:45:11
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: \learn\react-learn\src\redux\components\App.js
 */
import React from 'react'
import Footer from './Footer'
import AddTodo from '../containers/AddTodo'
import VisibleTodoList from '../containers/VisibleTodoList'

const App = () => (
  <div>
    <AddTodo />
    <VisibleTodoList />
    <Footer />
  </div>
)

export default App
