// 微前端/qiankun/react-dome/src/App.jsx
import Home from './view/home';
import About from './view/about';
import { connect } from 'react-redux'
import { Route, Redirect, Link, Switch, useRouteMatch } from 'react-router-dom'

import './style/App.css'


function App(props) {
  let { path, url } = useRouteMatch();
  console.log(path, url);
  const { token } = props
  if (!token) {
    return <Redirect to="/login" />;
  }
  return (
    <>
      <ul className="nav">
        <li className="menu">
          <Link to="/home">React Home</Link>
        </li>
        <li className="menu">
          <Link to={`${path}/about`}>React about</Link>
        </li>
        
      </ul>
      <div className="container">
        <div className="header" >Child Header</div>
        <div className="router-view">
          <Switch>
            <Route path={path} exact component={Home} >
            </Route>
            <Route path={`${path}/about`} component={About}>
            </Route>
          </Switch>
        </div>
      </div>
    </>
  );
}
export default connect((state) => state.token)(App);

// 微前端/qiankun/vue2-dome/src/App.vue
<template>
  <div class="main-container">
    <div class="nav" v-if="token">
      <div class="menu">
        <router-link to="/">Child Home</router-link>
      </div>
      <div class="menu">
        <router-link to="/about">Child About</router-link>
      </div>
    </div>
    <div class="container">
      <div class="header" v-if="token">Child Header</div>
      <div class="router-view">
        <router-view />
      </div>
    </div>
  </div>
</template>

<script>
import { mapState } from "vuex";

export default {
  computed: {
    ...mapState(["token"])
  }
};
</script>

<style>
#app, .main-container {
  display: flex;
  width: 100%;
  height: 100%;
}
.nav {
  width: 300px;
  height: 100%;
  border-right: 2px solid red;
}
.menu {
  width: 100%;
  background: gray;
  margin-bottom: 10px;
  height: 30px;
}
.menu > a {
  color: white;
}
.container {
  flex: 1;
}
.header {
  background: #ada5a5;
  width: 100%;
  height: 50px;
  color: white;
}
</style>
