// WebpackDome/webpack-vue/src/App.vue
<!--
 * @Author: your name
 * @Date: 2021-01-11 10:14:14
 * @LastEditTime: 2021-01-11 15:16:15
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: \learn\WebpackDome\webpack-vue\src\App.vue
-->
<template>
  <div class="example">
      <h1>{{ msg }}</h1>

  <img src="./assets/616945.png" alt="" srcset="">

  </div>
</template>

<script>
export default {
    name: "app",
  data () {
    return {
      msg: 'Hello world!'
    }
  }
}
</script>

<style>
.example {
  color: red;
}
</style>

// WebpackDome/webpack-react/src/app.jsx
/*
 * @Author: your name
 * @Date: 2021-01-08 15:35:11
 * @LastEditTime: 2021-01-08 17:59:31
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: \learn\WebpackDome\webpack-react\src\pages\app.js
 */
// import {Component} from 'react';
const React=require('react')
import bg from '@/img/616945.png'
class App extends React.Component{
    render(){
        return <div className='tit'>
            我是react 示例；
            
            <img src={bg} alt=""/>
        </div>
    }
}
export default App
